### ISSUE TITLE
How to use this code

### ISSUE THREAD

**Issue by otmezger** [miodeqqq/tournament#1]
Hi,

we will host a karate shotokan tournament early next year, and I was looking for a software that help us run the event. I just came across your project and was wondering if you could explain briefly how this code works. I might be interested in contributing to this project, but first I need help understanding what it is about.

thanks

**Comment by miodeqqq** [comment]
Hi,

Thanks for your message! Unfortunately, all of this templates have been made in polish language and honestly - I don't have time to translate them. This software has been made as a thesis and makes possibility to do exactly what's been written in review. There is my thesis and at page 42 there is an instruction how to use it. If you have any questions I would answer as soon as its possible :)

Thesis: http://maciekj.com.pl/diploma/praca_inzynierska.pdf

Best wishes - Maciek

**Comment by otmezger** [comment]
Oh thanks, my polish is not in a good shape :)

 nevertheless, your compilation of karate apps is nice. thanks for sharing.

**Comment by miodeqqq** [comment]
You're welcome :)

It's open source, so...

I wish you best!

2015-09-08 16:35 GMT+02:00 otmezger <notifications@github.com>:

> Oh thanks, my polish is not in a good shape :)
>
> nevertheless, your compilation of karate apps is nice. thanks for sharing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/miodeqqq/tournament/issues/1#issuecomment-138584497>.
>



-- 
Maciej Januszewski
